server:
    port: 80

spring:
    datasource:
#      platform: mysql
#      url: jdbc:mysql://192.168.0.21:3306/hobby?useUnicode=true&characterEncoding=utf8
#      username: simkungAdmin
#      password: eldhqlf406
#      driverClassName: com.mysql.jdbc.Driver
      hikari:
        jdbc-url: jdbc:mysql://192.168.0.21:3306/hobby?useUnicode=true&characterEncoding=utf8
        username: simkungAdmin
        password: eldhqlf406
        driver-class-name: com.mysql.jdbc.Driver




    jpa:
        show-sql: true
        generate-ddl: false
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            ddl-auto: validate
            naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy